mod auth;
mod db;
mod state;

use aide::{
    axum::{
        routing::{get, post},
        ApiRouter, IntoApiResponse,
    },
    openapi::{Info, OpenApi},
};
use axum::{Extension, Json};
use shuttle_runtime::CustomError;
use shuttle_secrets::{SecretStore, Secrets};
use sqlx::PgPool;

use state::MyState;

async fn hello_world() -> &'static str {
    "`glhf` API\n\
        \tDocumentation @ https://github.com/bfahrenfort/shuttle-glhf"
}

#[shuttle_runtime::main]
async fn main(
    #[Secrets] secrets: SecretStore,
    #[shuttle_shared_db::Postgres(
        local_uri = "postgres://postgres:{secrets.PASSWORD}@localhost:19087/postgres"
    )]
    pool: PgPool,
) -> shuttle_axum::ShuttleAxum {
    sqlx::migrate!()
        .run(&pool)
        .await
        .map_err(CustomError::new)?;

    let mut api = OpenApi {
        info: Info {
            title: "rsgistry".to_string(),
            description: Some("API generated by rsgistry".to_string()),
            ..Info::default()
        },
        ..OpenApi::default()
    };

    async fn serve_api(Extension(api): Extension<OpenApi>) -> impl IntoApiResponse {
        Json(api)
    }

    let state = MyState { pool, secrets };
    #[cfg(debug_assertions)]
    {
        let router = ApiRouter::new()
            .route("/api.json", get(serve_api))
            .route("/", get(hello_world))
            .api_route("/api/v1/debug/update", post(db::update::push))
            .api_route("/api/v1/update", get(db::update::auth_push))
            .api_route("/api/v1/queue/add", post(db::update::enqueue))
            .api_route("/api/v1/queue/peek", get(db::fetch::queue_peek))
            .api_route("/api/v1/queue/fetch", get(db::fetch::queue_fetch))
            .api_route("/api/v1/fetch/:name", get(db::fetch::retrieve))
            .api_route("/login", post(auth::login))
            .with_state(state);

        Ok(router.finish_api(&mut api).layer(Extension(api)).into())
    }

    #[cfg(not(debug_assertions))]
    {
        let router = ApiRouter::new()
            .route("/", get(hello_world))
            .api_route("/api/v1/update", get(db::update::auth_push))
            .api_route("/api/v1/queue/add", post(db::update::enqueue))
            .api_route("/api/v1/queue/peek", get(db::fetch::queue_peek))
            .api_route("/api/v1/queue/fetch", get(db::fetch::queue_fetch))
            .api_route("/api/v1/fetch/:name", get(db::fetch::retrieve))
            .api_route("/login", post(auth::login))
            .with_state(state);

        Ok(router.finish_api(&mut api).layer(Extension(api)).into())
    }
}
